// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWNsb3QY-SIfBCdAlB6bh0Ik3Nh331T3o',
    appId: '1:166880408763:web:78f07eb2686787bddf259e',
    messagingSenderId: '166880408763',
    projectId: 'daily-tracker-55976',
    authDomain: 'daily-tracker-55976.firebaseapp.com',
    storageBucket: 'daily-tracker-55976.firebasestorage.app',
    measurementId: 'G-N2KK7F22BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAygK-5SRf2ygqMEGjg_X72VZCdf9XGvxI',
    appId: '1:166880408763:android:fe722c2a859fa412df259e',
    messagingSenderId: '166880408763',
    projectId: 'daily-tracker-55976',
    storageBucket: 'daily-tracker-55976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXy7phGpbPsb91HhgCxXVbTUTzrsO2Uvs',
    appId: '1:166880408763:ios:dfd31d53fef4d9c0df259e',
    messagingSenderId: '166880408763',
    projectId: 'daily-tracker-55976',
    storageBucket: 'daily-tracker-55976.firebasestorage.app',
    iosBundleId: 'com.example.dailyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXy7phGpbPsb91HhgCxXVbTUTzrsO2Uvs',
    appId: '1:166880408763:ios:dfd31d53fef4d9c0df259e',
    messagingSenderId: '166880408763',
    projectId: 'daily-tracker-55976',
    storageBucket: 'daily-tracker-55976.firebasestorage.app',
    iosBundleId: 'com.example.dailyTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWNsb3QY-SIfBCdAlB6bh0Ik3Nh331T3o',
    appId: '1:166880408763:web:1a35ab3644395667df259e',
    messagingSenderId: '166880408763',
    projectId: 'daily-tracker-55976',
    authDomain: 'daily-tracker-55976.firebaseapp.com',
    storageBucket: 'daily-tracker-55976.firebasestorage.app',
    measurementId: 'G-FPNTG9NS9P',
  );
}
