// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdZ0ep7tZMbC2s4zYylU_kh9jg_x2Z4Ps',
    appId: '1:437645280885:web:fe75aadb2abb569d115a3c',
    messagingSenderId: '437645280885',
    projectId: 'daily-tracker-fc325',
    authDomain: 'daily-tracker-fc325.firebaseapp.com',
    storageBucket: 'daily-tracker-fc325.firebasestorage.app',
    measurementId: 'G-XDX2GGWBS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8TPFVTdAzNZeZ3n1AHY5J6kDeGZ3IPGY',
    appId: '1:437645280885:android:4e68433e84cc6c09115a3c',
    messagingSenderId: '437645280885',
    projectId: 'daily-tracker-fc325',
    storageBucket: 'daily-tracker-fc325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhAQ2Vt8yo2GBIj0Z43BIqB7SyFTLEUY',
    appId: '1:437645280885:ios:995317e621c51884115a3c',
    messagingSenderId: '437645280885',
    projectId: 'daily-tracker-fc325',
    storageBucket: 'daily-tracker-fc325.firebasestorage.app',
    iosBundleId: 'com.example.expensesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWhAQ2Vt8yo2GBIj0Z43BIqB7SyFTLEUY',
    appId: '1:437645280885:ios:995317e621c51884115a3c',
    messagingSenderId: '437645280885',
    projectId: 'daily-tracker-fc325',
    storageBucket: 'daily-tracker-fc325.firebasestorage.app',
    iosBundleId: 'com.example.expensesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdZ0ep7tZMbC2s4zYylU_kh9jg_x2Z4Ps',
    appId: '1:437645280885:web:06d362903b68e633115a3c',
    messagingSenderId: '437645280885',
    projectId: 'daily-tracker-fc325',
    authDomain: 'daily-tracker-fc325.firebaseapp.com',
    storageBucket: 'daily-tracker-fc325.firebasestorage.app',
    measurementId: 'G-CYDMBCF7EP',
  );
}
